# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnImediate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnImediate

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'CenteredCollectionView'

  target 'AnImediateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnImediateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
