# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnImediate' do

  use_frameworks!

  # Pods for AnImediate

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'MXParallaxHeader'
  pod 'Tabman', '2.5.0'
  pod 'RSKImageCropper'
  pod 'Firebase/Database'
  pod 'CenteredCollectionView'
  pod 'RealmSwift'
  pod 'ReSwift', '4.1.1'
  pod 'RxSwift', '4.5'
  pod 'RxCocoa', '4.5'
  pod 'Swinject', '2.6.2'
  pod 'SwinjectStoryboard'
  pod 'SwiftRichString', '2.1.0'
  pod 'Sourcery'

  target 'AnImediateTests' do
    inherit! :search_paths
  end

  target 'AnImediateUITests' do
    inherit! :search_paths
  end

  target 'AppConfig' do
    inherit! :search_paths
  end

  target 'AppModel' do
    inherit! :search_paths
  end

end
