# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnImediate' do

  use_frameworks!

  # Pods for AnImediate

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'MXParallaxHeader', '1.0.0'
  pod 'Tabman', '2.5.0'
  pod 'RSKImageCropper', '2.2.3'
  pod 'CenteredCollectionView', '2.2.1'
  pod 'RealmSwift', '3.18.0'
  pod 'ReSwift', '4.1.1'
  pod 'RxSwift', '4.5'
  pod 'RxCocoa', '4.5'
  pod 'RxDataSources', '3.1.0'
  pod 'Swinject', '2.6.2'
  pod 'SwinjectStoryboard', '2.2.0'
  pod 'SwiftRichString', '2.1.0'
  pod 'Sourcery', '0.17.0'
  pod 'SwiftGen', '6.1.0'
  pod 'IBAnimatable', '6.0.0'

  target 'AnImediateTests' do
    inherit! :search_paths
  end

  target 'AnImediateUITests' do
    inherit! :search_paths
  end

  target 'AppConfig' do
    inherit! :search_paths
  end

  target 'AppModel' do
    inherit! :search_paths
  end

  target 'RxMultiPeerWrapper' do
    inherit! :search_paths
  end


end
